### ISSUE TITLE
能在地图上画Label不？

### ISSUE THREAD

**Issue by terry8204** [Wayaer/fl_amap_map#1]
官方的我们试下了下，不能画Label

**Comment by Wayaer** [comment]
这个只是把官方的插件拉下来  升级下2.0而已，没有添加任何api

**Comment by terry8204** [comment]
收到，谢谢，百度的可以了，改用百度，没办法。



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2021年4月29日(周四) 下午2:21
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [Wayaer/amap_flutter_map] 能在地图上画Label不？ (#1)




 
这个只是把官方的插件拉下来  升级下2.0而已，没有添加任何api
