### ISSUE TITLE
这个插件没有上 pub.dev 吗？

### ISSUE THREAD

**Issue by Wing-Li** [Wayaer/fl_amap_map#1]
那个插件只有单纯的定位的功能。

使用那个定位的插件之后，如果我还要显示地图，集成了官方的地图 amap_flutter_map 之后 Android 需要引入 com.amap.api:3dmap:9.7.0 的包。

但是那个定位的插件引入了 com.amap.api:location:6.2.0 的包。 3dmap 和 loadtion 的包 是冲突的！！！！

**Comment by Wing-Li** [comment]
或者能不能把插件里面的 com.amap.api:location:6.2.0 包去掉，让用户自己集成，写在文档里。

**Comment by Wayaer** [comment]
你说的 compileOnly  应该是 `fl_amp`(这只是个定位包),compileOnly 不能解决问题，只能解决编译打包的问题，但是项目单纯只是定位，就会报错。这个 `fl_amap_map`
就是支持定位和地图，但是还在开发中，3dmap 9.0 以下跟 loadtion 不会冲突，况且用了`amap_flutter_map` 9.0还会闪退，官方也一直不更新，

**Comment by Wing-Li** [comment]
在 Android 引入这两个版本，就好了。 location版本不能太低，否则没有隐私政策方法。

    //高德地图功能 // 3dmap 使用8.1.0–9.2.1版本，不包含 location 库
    implementation 'com.amap.api:3dmap:9.2.1'
    implementation 'com.amap.api:location:6.1.0'
